### ISSUE TITLE
`wasm-bindgen-wasm-interpreter` can't handle extra block

### ISSUE THREAD

**Issue by Niedzwiedzw** [wasm-bindgen/wasm-bindgen#3315]
```
Finished release [optimized] target(s) in 0.08s
[INFO]: License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'unknown instruction Block(Block { seq: Id { idx: 1 } })', crates/wasm-interpreter/src/lib.rs:367:18
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: wasm_bindgen_wasm_interpreter::Interpreter::call
   3: wasm_bindgen_wasm_interpreter::Interpreter::interpret_descriptor
   4: wasm_bindgen_cli_support::descriptors::execute
   5: wasm_bindgen_cli_support::Bindgen::generate_output
   6: wasm_bindgen_cli_support::Bindgen::generate
   7: wasm_bindgen::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 101
  full command: "/home/niedzwiedz/.cache/.wasm-pack/wasm-bindgen-5f26acfc988649a3/wasm-bindgen" "/home/niedzwiedz/crionis/crio-app/target/wasm32-unknown-unknown/release/editor.wasm" "--out-dir" "/home/niedzwiedz/crionis/crio-app/pkg" "--typescript" "--target" "bundler" "--out-name" "index"
```

EDIT: https://github.com/rustwasm/wasm-pack/issues/1229 <- I've opened this issue here to, cause I have no idea what causes the bug

EDIT: https://github.com/rustwasm/wasm-bindgen/blob/629a623adfe27c67a21408c120d3466965575e45/crates/wasm-interpreter/src/lib.rs#L367 this is the line that crashes

**Comment by csnover** [comment]
I encountered the `unknown instruction Block` panic as well trying to compile a library to wasm32-wasi and discovered that this is because the bindgen descriptor interpreter is trying to call through `__wasm_call_ctors` and `__wasm_call_dtors`, at least the former of which contains complex functions that the interpreter isn’t designed to handle. According to [this ticket](https://github.com/WebAssembly/WASI/issues/471), LLVM 13 changed its default output to include these in exported functions by default. Looking at the output of the compiler, it seems that the [`-Zwasi-exec-model` flag](https://github.com/rust-lang/rust/pull/79997) in a nightly compiler may suppress these extra calls, but in any case wasm-bindgen probably should just be updated to avoid calling them since they aren’t relevant to what it is doing.

**Comment by Liamolucko** [comment]
> I encountered the `unknown instruction Block` panic as well trying to compile a library to wasm32-wasi and discovered that this is because the bindgen descriptor interpreter is trying to call through `__wasm_call_ctors` and `__wasm_call_dtors`, at least the former of which contains complex functions that the interpreter isn’t designed to handle. According to [this ticket](https://github.com/WebAssembly/WASI/issues/471), LLVM 13 changed its default output to include these in exported functions by default. Looking at the output of the compiler, it seems that the [`-Zwasi-exec-model` flag](https://github.com/rust-lang/rust/pull/79997) in a nightly compiler may suppress these extra calls, but in any case wasm-bindgen probably should just be updated to avoid calling them since they aren’t relevant to what it is doing.
> 
> This is probably a duplicate of #2673.

Yeah, I think your issue is the same as #2673 (and #2969), but I'm not so sure about @Niedzwiedzw's. They're using `wasm-pack`, and `wasm-pack` compiles for `wasm32-unknown-unknown`, not `wasm32-wasi`, so I don't see how they could be running into that issue.

@Niedzwiedzw, could you give some instructions for how to reproduce this?

**Comment by Michael-F-Bryan** [comment]
@daxpedda can you re-open this ticket? The OP was actually compiling to `wasm32-unknown-unknown` (you can see `crio-app/target/wasm32-unknown-unknown/release` in their error message), so this issue isn't related to `wasm32-wasi`.

I'm running into the exact same issue compiling `wasmer/wasmer-js` to `wasm32-unknown-unknown` using `wasm-pack`.

**Comment by Michael-F-Bryan** [comment]
I did some more troubleshooting for this and found that the underlying cause was the `#[tracing::instrument]` attribute I added to my `#[wasm_bindgen]` function. 

When compiling without optimisations mode, this introduces extra [`Instr::Block`](https://docs.rs/walrus/latest/walrus/ir/enum.Instr.html#variant.Block) and [`Instr::BrIf`](https://docs.rs/walrus/latest/walrus/ir/enum.Instr.html#variant.BrIf) instructions that the minimal wasm interpreter used by `wasm-bindgen` can't handle.

In my case, all I needed to do was remove the `#[tracing::instrument]` calls and start the span inside the functions.

```diff
 #[wasm_bindgen]
 impl Instance {
     /// Wait for the process to exit.
-    #[tracing::instrument(level = "debug", skip_all)]
     pub async fn wait(self) -> Result<JsOutput, Error> {
+        let _span = tracing::debug_span!("wait").entered();
+
         let Instance {
             stdin,
             stdout,
```

**Comment by daxpedda** [comment]
Thank you for looking into it!

**Comment by seancribbs** [comment]
To add additional context since I just investigated this myself (also related to `tracing::instrument`), the codegen **unconditionally** emits the attributes attached to the original function onto the generated bindgen and descriptor functions. Is the rationale for this behavior to support conditional compilation?

Would it be useful to have an option for the `wasm_bindgen` macro that lets you filter out attributes with specific names? I could see that being straightforward to add and would be willing to try.

**Comment by HarukaMa** [comment]
In my case, it's `wasm-opt` which generates block instructions (`-O2` and above) instead of directly generated by the compiler. Only happens with certain code, can't find any pattern for that.

**Comment by daxpedda** [comment]
If understand that correctly you are using `wasm-bindgen-cli` after processing the file with `wasm-opt`.
But you have to use `wasm-opt` **after** processing the file with `wasm-bindgen`!

**Comment by HarukaMa** [comment]
didn't know the order mattered as it was working fine for me. guess I just got super lucky or something like that. Thanks for the tip!

**Comment by Spxg** [comment]
I believe this issue is caused by interpreting `__wasm_call_ctors`. v0.2.101 has been released, which fixes this issue.

If the issue persists, please report it again!

**Comment by jpochyla** [comment]
@Spxg 0.2.101 does work, but upgrading to 0.2.102 seems to break again for me:

```
thread 'main' panicked at /Users/jpochyla/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wasm-bindgen-cli-support-0.2.102/src/interpreter/mod.rs:218:21:
wasm_bindgen::__rt::wbg_cast::breaks_if_inlined::h0032533367285740: unknown instruction Block(Block { seq: Id { idx: 1 } })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I don't use `tracing`, it's hard to pinpoint the culprit.

**Comment by Spxg** [comment]
> I don't use tracing, it's hard to pinpoint the culprit.

Is there a reproducible case?
